sudo: required

language: cpp

env:
    global:
        - CMAKE_VERSION="cmake-3.4.0-Linux-x86_64"
        - CMAKE_BINARY="${CMAKE_VERSION}/bin/cmake"

addons:
    apt:
        sources:
            - llvm-toolchain-precise-3.7
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.7
            - g++-5
            - gcc-5
            - wget
            - libev-dev

compiler:
  - gcc
  - clang

before_install:
    - wget https://cmake.org/files/v3.4/cmake-3.4.0-Linux-x86_64.tar.gz --no-check-certificate
    - tar -xzvf cmake-3.4.0-Linux-x86_64.tar.gz
    - wget http://sourceforge.net/projects/asio/files/asio/1.10.6%20%28Stable%29/boost_asio_1_10_6.tar.gz/download
    - mv download asio-1.10.6.tar.gz
    - tar xvf asio-1.10.6.tar.gz
    - ls
    - ls boost_asio_1_10_6

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi

before_script:
    - echo $CC
    - echo $CXX
    - $CXX --version
    - $CC --version
    - ${CMAKE_BINARY} --version
    - ${CMAKE_BINARY} .
    - make

script:
  - ./test_hermes
