sudo: required

language: cpp

env:
    global:
        - CMAKE_VERSION="cmake-3.4.0-Linux-x86_64"
        - CMAKE_BINARY="${CMAKE_VERSION}/bin/cmake"

addons:
    apt:
        sources:
            - llvm-toolchain-precise-3.7
            - ubuntu-toolchain-r-test
        packages:
            - g++-5
            - gcc-5
            - wget
            - libev-dev

compiler:
  - gcc

before_install:
    - wget https://cmake.org/files/v3.4/cmake-3.4.0-Linux-x86_64.tar.gz --no-check-certificate
    - tar -xzvf cmake-3.4.0-Linux-x86_64.tar.gz
    - wget https://github.com/google/protobuf/releases/download/v3.0.0-beta-2/protobuf-cpp-3.0.0-beta-2.tar.gz
    - tar xzvf protobuf-cpp-3.0.0-beta-2.tar.gz
    - cd  protobuf-3.0.0-beta-2
    - ./configure
    - sudo make install
    - cd -
    - wget http://sourceforge.net/projects/boost/files/boost/1.59.0/boost_1_59_0.tar.gz
    - tar xvf boost_1_59_0.tar.gz
    - cd boost_1_59_0
    - ./bootstrap.sh --prefix=/home/travis
    - ./b2 install
    - cd -

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

before_script:
    - echo $CC
    - echo $CXX
    - $CXX --version
    - $CC --version
    - ${CMAKE_BINARY} --version
    - ${CMAKE_BINARY} .
    - make

script:
  - ./test_hermes
